title: Cícero Quintino Junior
subtitle: Ciência de Dados | IA | Machine Learning | Back-end Developer
description: >-
  Portfólio de Cícero Quintino Junior, profissional apaixonado por Data Science, Inteligência Artificial e Desenvolvimento Back-end com Java e Python.
author: Cícero Quintino Junior
email: cicerojr10@gmail.com
avatar: assets/images/avatar.jpg

baseurl: "" # Para domínio próprio, deixe vazio
url: "https://cicerojrtechprofessional.software" # Inclua o protocolo https!
lang: "pt-BR"

instagram_url: https://www.instagram.com/ciceroqjunior
linkedin_url: https://www.linkedin.com/in/cicerojr-techprofessional/
github_url: https://github.com/cicerojr10


theme: jekyll-theme-prologue
collections: [sections]
