title: "Cícero Quintino Junior"
tagline: "Ciência de Dados | IA | Machine Learning | Back-end Developer"
description: >
  Portfólio de Cícero Quintino Junior, profissional apaixonado por Data Science, Inteligência Artificial e Desenvolvimento Back-end com Java e Python.
url: "https://cicerojrtechprofessional.software"
lang: "pt-BR"
timezone: "America/Sao_Paulo"
avatar: "/assets/images/avatar.png"
github: cicerojr10
linkedin: "https://www.linkedin.com/in/cicerojr-techprofessional/"
instagram: "https://www.instagram.com/ciceroqjunior"
email: "cicerojr10@gmail.com"
theme: jekyll-theme-chirpy

author:
  name: "Cícero Quintino Junior"
  bio: "Ciência de Dados, IA, Machine Learning, Back-end Developer"
  email: "cicerojr10@gmail.com"
  avatar: "/assets/images/avatar.png"

social:
  name: "Cícero Quintino Junior"
  links:
    - https://github.com/cicerojr10
    - https://www.linkedin.com/in/cicerojr-techprofessional/
    - https://www.instagram.com/ciceroqjunior

google_analytics:
  id: "G-NTEQ4DX884"

nav:
  - name: About
    url: /about/
  - name: Projects
    url: /projects/
  - name: Skills
    url: /skills/
  - name: Contact
    url: /contact/
