title: "Cícero Quintino Junior"
subtitle: "Ciência de Dados | IA | Machine Learning | Back-end Developer"
description: >
  Portfólio de Cícero Quintino Junior, profissional apaixonado por Data Science, Inteligência Artificial e Desenvolvimento Back-end com Java e Python.
author: "Cícero Quintino Junior"
email: "cicerojr10@gmail.com"
avatar: "assets/images/avatar.jpg"
logo: "/assets/images/logo.svg"

lang: "pt-BR"
baseurl: "" # Para domínio próprio, deixe vazio
url: "https://cicerojrtechprofessional.software" # Inclua o protocolo https!
favicon: "/assets/images/favicon.ico" # Se tiver favicon, coloque o caminho

# Social links padronizados (para facilitar chamadas no layout)
social:
  instagram: "https://www.instagram.com/ciceroqjunior"
  linkedin: "https://www.linkedin.com/in/cicerojr-techprofessional/"
  github: "https://github.com/cicerojr10"

# Plugins recomendados para SEO e sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Coleções personalizadas
collections:
  sections:
    output: true

# Tema do Jekyll
theme: minima

# Google Analytics (tema minima)
google_analytics: G-NTEQ4DX884

# SEO/opengraph (opcional, melhora preview em redes sociais)
defaults:
  -
    scope:
      path: ""
    values:
      image: "assets/images/banner.jpg" # banner para preview social
